export const USER_LOADED = 'USER_LOADED';
export const USERS_SEARCH_RESULT = 'USERS_SEARCH_RESULT';
export const REPOSITORIES_LOADED = 'REPOSITORIES_LOADED';
export const REPOSITORIES_FILTERED = 'REPOSITORIES_FILTERED';
export const ADD_ALERT = 'ADD_ALERT';
